#ifndef DWKEYBOARD_GLOBAL_H
#define DWKEYBOARD_GLOBAL_H

#if defined(DWKEYBOARD_LIBRARY)
#  define DWKEYBOARDSHARED_EXPORT Q_DECL_EXPORT
#else
#  define DWKEYBOARDSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // DWKEYBOARD_GLOBAL_H
